#!/usr/bin/env tsx
/**
 * Build the lightweight fallback index consumed by the DeFiLlama browser-extension
 * showcase (../../extension).
 *
 * Reuses the exact server-side rendering logic the website uses
 * (assessProtocol / deriveTier / getProtocolMetadata) so the extension matches
 * defipunkd.com without reimplementing any grading. One record per protocol
 * that has at least one assessment.
 *
 * Emits one artifact:
 *   - extension/src/index-fallback.js   (lightweight index assigned to
 *                                        globalThis.DEFIPUNKD_INDEX_FALLBACK;
 *                                        used by the extension when the live API
 *                                        is unreachable)
 *
 * The full ProtocolRecord map (with about/pills/verdict) is served live via the
 * /api/extension/* API routes instead of being bundled into the extension.
 *
 * Run: pnpm --filter @defipunkd/web build:extension-data
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildExtensionMap, toIndex } from "../src/lib/extension-data";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..", "..", "..");
const OUT_DIR = join(REPO_ROOT, "extension");

function main(): void {
  const map = buildExtensionMap();
  const index = toIndex(map);

  mkdirSync(join(OUT_DIR, "src"), { recursive: true });

  const banner =
    "// AUTO-GENERATED by apps/web/scripts/build-extension-data.ts — do not edit by hand.\n" +
    "// Run `pnpm --filter @defipunkd/web build:extension-data` to refresh.\n";
  const fallbackJs = `${banner}globalThis.DEFIPUNKD_INDEX_FALLBACK = ${JSON.stringify(index, null, 2)};\n`;
  const outPath = join(OUT_DIR, "src", "index-fallback.js");
  writeFileSync(outPath, fallbackJs);

  const protocolCount = Object.keys(index).length;
  const fileSizeKb = Math.round(Buffer.byteLength(fallbackJs) / 1024);
  console.log(
    `[build-extension-data] wrote ${protocolCount} protocols → extension/src/index-fallback.js (${fileSizeKb} KB)`,
  );
}

main();
