export const accessBody = `### Slice: ACCESS

Evaluate who is allowed to use the protocol and whether any of that permission is granted off-chain.

Scope: this slice is about ADMISSION — who can enter, exit, or transact. Operator LIVENESS (what breaks if keepers/oracles go offline) is assessed in the dependencies slice and is out of scope for the grade here. You may note operator dependencies as context, but do not let "the protocol halts if operator X disappears" drive the access grade on its own; that belongs in dependencies.

Meta-check before finalizing: if your verdict cites phrases from this prompt as evidence ("the protocol meets the 'credible alternatives' condition", "this fits the 'documented fallback' rule"), redo the verdict. The prompt describes the rubric; evidence must come from the protocol. A verdict should cite what the protocol does, not what the rubric says.

MANDATORY INSPECTION CHECKLIST (every item below must appear in evidence[] OR unknowns[]):
- A1. Whitelist / allowlist modifiers in user-facing entry points. Grep for "onlyWhitelisted", "onlyRole", "allowlist", "isAccredited", "isKYCed". Note which functions are gated and who can add/remove from the list.
- A2. Off-chain operators in the admission path: keepers, sequencers, privileged relayers, oracle posters whose approval is required to admit a user action (not just to keep the protocol live). For each, identify whether the role is held by a single operator, a permissioned committee, or is permissionless. Enumerate per user-facing function class (deposit vs withdraw-request vs claim-finalized vs transfer) which ones require operator approval to be admitted, and which ones admit users unconditionally. A function whose placement is unconditional but whose downstream settlement depends on an operator is an admission-permissionless function — flag the liveness dependency as context and defer its grading weight to the dependencies slice.
- A3. Frontend restrictions on the official interface. Distinguish two tiers, because they are weighted very differently at grading time:
    - A3-passive: boilerplate ToS clauses (sanctions attestation, restricted-territory self-certification, VPN-circumvention prohibition, "comply with applicable law" eligibility, age of majority). These are ubiquitous on DeFi frontends and carry little grade weight on their own.
    - A3-active: the frontend actively enforces a restriction at runtime — IP-based geo-blocking (user in country X is redirected or blocked), wallet-address screening (connected wallet is checked against a sanctions oracle like Chainalysis or TRM and rejected), a KYC wall (user must submit identity documents before using the app), or "not available in your jurisdiction" banner that prevents the UI from rendering.
  Load protocol.website (or check screenshots / archive) and record findings under the correct tier. Quote the relevant ToS text or reproduce the block banner text in evidence[].shows.
  Evidentiary floor for A3-active: because A3-active is grade-determinative (it pushes green → orange), an A3-active finding MUST cite at least one of: (a) a verbatim block-banner or rejection message quoted from the live site, (b) a specific network-layer observation (e.g. HTTP 451 from a specific country, a geo-redirect URL), (c) a named third-party screening provider visibly integrated into the page (Chainalysis Oracle, TRM, Elliptic) with a URL, script tag, or commit SHA proving the integration, or (d) a public incident report documenting enforcement. Do NOT infer A3-active from ToS text: a clause that says the Interface is prohibited for ineligible users describes a policy, not an enforcement mechanism. Do NOT infer A3-active from prior knowledge about DeFi-frontend practices. Absent evidence of type (a)–(d), an A3-active claim belongs in unknowns[] ("could not verify active enforcement from static fetch") rather than in findings[] as an asserted restriction.
- A3b. Alternative access paths documented by the protocol itself. Split findings into two classes, because they weigh differently:
    - A3b-i: Redistributions of the official frontend that remain bound by the same ToS — e.g. IPFS-pinned releases of the official UI, mirrors of the official widget. Record CIDs/URLs. Also check whether the ToS's definition of "Interface" (or equivalent) covers these redistributions, and whether the ToS prohibits VPN/anti-geo circumvention. If the same ToS applies, a redistribution is NOT an independent access path for grading purposes.
    - A3b-ii: Independent paths not bound by the official ToS — direct-contract interaction (docs, SDK, CLI, command-line examples), third-party frontends operated by separate legal entities, wallet-integrated access (e.g. MetaMask/Safe integrations). Record links. Only A3b-ii paths count as mitigation against official-frontend ToS restrictions when grading.
- A4. Sanctions / compliance tooling: does the protocol check addresses against OFAC lists or similar onchain blocklists?
- A5. Differentiate read access vs write access: many protocols are read-permissionless (anyone can view state) but write-gated (only certain addresses can deposit/borrow). Record both.
- A6. ToS / Legal links: locate them on the website and produce a VERBATIM quote of any jurisdictional, sanctions, or eligibility clause in evidence[].shows. If you cannot extract the clause text verbatim (SPA render failure, paywall, dead link, etc.), do NOT paraphrase or infer from general knowledge — record the ToS URL in unknowns[] with the reason extraction failed. Assertions about ToS content without a verbatim quote will be downweighted by reviewers.

Then write the steel-man section per Hard Rule 11.

Grade rules (admission-focused; liveness concerns belong in dependencies):
- green   = no contract-level whitelist/KYC on user entry/exit; no operator approval required to admit a user action; AND no A3-active restrictions on the official frontend. A3-passive boilerplate ToS clauses (sanctions attestation, VPN prohibition, restricted-territory self-certification) are compatible with green — they are standard across DeFi and do not materially gate admission by themselves. A3b-ii paths (independent third-party frontends, documented direct-contract access) reinforce a green grade but are not required for it when the only frontend restriction is passive ToS.
- orange  = contracts admit users unconditionally, but the official frontend applies A3-active enforcement (IP geo-blocking, wallet-address screening, KYC wall, or rendering-blocking jurisdiction banner) AND independent A3b-ii alternative paths are absent, poorly documented, or accessible only to technical users. Also applies when an admission path requires approval from a permissioned committee that is governance-managed with a documented replacement procedure. A3-passive ToS alone does NOT justify orange — a passive ToS restriction is a ~0.25-severity signal, not a grade downgrade.
- red     = contract-level whitelist / KYC on user entry/exit, OR admission of a core user action requires approval from a single privileged operator or a small committee with no documented replacement procedure, OR enforces an onchain blocklist updatable by a single party.
- unknown = checklist incomplete after checking the sources above.

Guideline on committees: where admission depends on a multi-operator committee, the relevant axes are (a) set size, (b) whether replacement/rotation is governed on-chain, (c) whether the replacement procedure is publicly documented. A large set with on-chain governance replacement should not be graded as a single-party operator even if rotation is not instantaneous. A small set with informal replacement should be treated as a single-party operator.`;
