export const accessBody = `### Slice: ACCESS

Evaluate who is allowed to use the protocol and whether any of that permission is granted off-chain.

Scope: this slice is about ADMISSION — who can enter, exit, or transact. Operator LIVENESS (what breaks if keepers/oracles go offline) is assessed in the dependencies slice and is out of scope for the grade here. You may note operator dependencies as context, but do not let "the protocol halts if operator X disappears" drive the access grade on its own; that belongs in dependencies.

Meta-check before finalizing: if your verdict cites phrases from this prompt as evidence ("the protocol meets the 'credible alternatives' condition", "this fits the 'documented fallback' rule"), redo the verdict. The prompt describes the rubric; evidence must come from the protocol. A verdict should cite what the protocol does, not what the rubric says.

MANDATORY INSPECTION CHECKLIST (every item below must appear in evidence[] OR unknowns[]):
- A1. Whitelist / allowlist modifiers in user-facing entry points. Grep for "onlyWhitelisted", "onlyRole", "allowlist", "isAccredited", "isKYCed". Note which functions are gated and who can add/remove from the list.
- A2. Off-chain operators in the admission path: keepers, sequencers, privileged relayers, oracle posters whose approval is required to admit a user action (not just to keep the protocol live). For each, identify whether the role is held by a single operator, a permissioned committee, or is permissionless. Enumerate per user-facing function class (deposit vs withdraw-request vs claim-finalized vs transfer) which ones require operator approval to be admitted, and which ones admit users unconditionally. A function whose placement is unconditional but whose downstream settlement depends on an operator is an admission-permissionless function — flag the liveness dependency as context and defer its grading weight to the dependencies slice.
- A3. Frontend restrictions on the official interface: load protocol.website (or check screenshots / archive) for ToS jurisdictional exclusions, geo-blocking (IP redirects), KYC walls, or "not available in your jurisdiction" banners. Quote the relevant text in evidence[].shows.
- A3b. Alternative access paths documented by the protocol itself. Split findings into two classes, because they weigh differently:
    - A3b-i: Redistributions of the official frontend that remain bound by the same ToS — e.g. IPFS-pinned releases of the official UI, mirrors of the official widget. Record CIDs/URLs. Also check whether the ToS's definition of "Interface" (or equivalent) covers these redistributions, and whether the ToS prohibits VPN/anti-geo circumvention. If the same ToS applies, a redistribution is NOT an independent access path for grading purposes.
    - A3b-ii: Independent paths not bound by the official ToS — direct-contract interaction (docs, SDK, CLI, command-line examples), third-party frontends operated by separate legal entities, wallet-integrated access (e.g. MetaMask/Safe integrations). Record links. Only A3b-ii paths count as mitigation against official-frontend ToS restrictions when grading.
- A4. Sanctions / compliance tooling: does the protocol check addresses against OFAC lists or similar onchain blocklists?
- A5. Differentiate read access vs write access: many protocols are read-permissionless (anyone can view state) but write-gated (only certain addresses can deposit/borrow). Record both.
- A6. ToS / Legal links: locate them on the website and produce a VERBATIM quote of any jurisdictional, sanctions, or eligibility clause in evidence[].shows. If you cannot extract the clause text verbatim (SPA render failure, paywall, dead link, etc.), do NOT paraphrase or infer from general knowledge — record the ToS URL in unknowns[] with the reason extraction failed. Assertions about ToS content without a verbatim quote will be downweighted by reviewers.

Then write the steel-man section per Hard Rule 11.

Grade rules (admission-focused; liveness concerns belong in dependencies):
- green   = no contract-level whitelist/KYC on user entry/exit; no operator approval required to admit a user action; AND the official frontend imposes no jurisdictional/KYC/geo restriction. A3b-ii paths (independent third-party frontends or documented direct-contract access not bound by the official ToS) are a contributing factor that can lift an otherwise-orange protocol to green only when those paths are prominently documented and usable by non-technical end users. A3b-i paths (IPFS redistributions of the same frontend under the same ToS) are informational and do not lift the grade on their own.
- orange  = contracts admit users unconditionally, but the official frontend restricts admission via ToS jurisdictional exclusions, geo-blocking, or KYC walls, and independent alternative paths (A3b-ii) are absent, poorly documented, or accessible only to technical users. Also applies when an admission path requires approval from a permissioned committee that is governance-managed with a documented replacement procedure.
- red     = contract-level whitelist / KYC on user entry/exit, OR admission of a core user action requires approval from a single privileged operator or a small committee with no documented replacement procedure, OR enforces an onchain blocklist updatable by a single party.
- unknown = checklist incomplete after checking the sources above.

Guideline on committees: where admission depends on a multi-operator committee, the relevant axes are (a) set size, (b) whether replacement/rotation is governed on-chain, (c) whether the replacement procedure is publicly documented. A large set with on-chain governance replacement should not be graded as a single-party operator even if rotation is not instantaneous. A small set with informal replacement should be treated as a single-party operator.`;
