export const accessBody = `### Slice: ACCESS

Evaluate who is allowed to use the protocol and whether any of that permission is granted off-chain.

Scope: this slice is about ADMISSION — who can enter, exit, or transact. Operator LIVENESS (what breaks if keepers/oracles go offline) is assessed in the dependencies slice and is out of scope for the grade here. You may note operator dependencies as context, but do not let "the protocol halts if operator X disappears" drive the access grade on its own; that belongs in dependencies.

MANDATORY INSPECTION CHECKLIST (every item below must appear in evidence[] OR unknowns[]):
- A1. Whitelist / allowlist modifiers in user-facing entry points. Grep for "onlyWhitelisted", "onlyRole", "allowlist", "isAccredited", "isKYCed". Note which functions are gated and who can add/remove from the list.
- A2. Off-chain operators in the admission path: keepers, sequencers, privileged relayers, oracle posters whose approval is required to admit a user action (not just to keep the protocol live). For each, identify whether the role is held by a single operator, a permissioned committee, or is permissionless. Enumerate per user-facing function class (deposit vs withdraw-request vs claim-finalized vs transfer) which ones require operator approval to be admitted, and which ones admit users unconditionally. A function whose placement is unconditional but whose downstream settlement depends on an operator is an admission-permissionless function — flag the liveness dependency as context and defer its grading weight to the dependencies slice.
- A3. Frontend restrictions on the official interface: load protocol.website (or check screenshots / archive) for ToS jurisdictional exclusions, geo-blocking (IP redirects), KYC walls, or "not available in your jurisdiction" banners. Quote the relevant text in evidence[].shows.
- A3b. Alternative permissionless access paths documented by the protocol itself: IPFS-hosted release of the official UI (record the CID or gateway URL), a self-hosted frontend repo users can run locally, documented third-party frontends/integrations, or explicit docs that direct users to interact with the contracts directly. Record links. The presence of credible alternatives materially weakens frontend-only restrictions; their absence strengthens them.
- A4. Sanctions / compliance tooling: does the protocol check addresses against OFAC lists or similar onchain blocklists?
- A5. Differentiate read access vs write access: many protocols are read-permissionless (anyone can view state) but write-gated (only certain addresses can deposit/borrow). Record both.
- A6. ToS / Legal links: locate them on the website and produce a VERBATIM quote of any jurisdictional, sanctions, or eligibility clause in evidence[].shows. If you cannot extract the clause text verbatim (SPA render failure, paywall, dead link, etc.), do NOT paraphrase or infer from general knowledge — record the ToS URL in unknowns[] with the reason extraction failed. Assertions about ToS content without a verbatim quote will be downweighted by reviewers.

Then write the steel-man section per Hard Rule 11.

Grade rules (admission-focused; liveness concerns belong in dependencies):
- green   = no contract-level whitelist/KYC on user entry/exit; no operator approval required to admit a user action; official frontend imposes no jurisdictional/KYC/geo restriction, OR credible permissionless alternatives (IPFS release, self-hosted widget, documented third-party frontends, direct-contract instructions) are prominently documented.
- orange  = contracts admit users unconditionally, but the official frontend restricts admission via ToS jurisdictional exclusions, geo-blocking, or KYC walls, AND alternative access paths are absent or poorly documented. Also applies when an admission path requires approval from a permissioned committee that is governance-managed with a documented replacement procedure (i.e. a "documented fallback" — large multi-operator set, on-chain replacement, published rotation). Prefer orange over red for large (>5) multi-operator committees with on-chain governance replacement, even if rotation is not instantaneous, because admission is not controlled by a single party.
- red     = contract-level whitelist / KYC on user entry/exit, OR admission of a core user action requires approval from a single privileged operator (or a small committee with no documented replacement procedure), OR enforces an onchain blocklist updatable by a single party.
- unknown = checklist incomplete after checking the sources above.`;
