export const autonomyBody = `### Slice: AUTONOMY

Evaluate this protocol's autonomy: can a failure of anything outside its own contracts cause theft or loss of user principal, loss of unclaimed yield, or materially change the protocol's expected performance? "Autonomy" is not "has zero external touchpoints" — it is "external failures are either survivable or recoverable without user loss". This slice adapts DefiScan v1's Autonomy dimension; dependencies are one of several criteria, not the whole frame.

GUARDRAILS (read before grading):
- Category alone (Liquid Staking, Bridge, RWA Lending, Restaking, …) does NOT force a grade. A category is a hint about where to look; the grade must come from the concrete A1–A9 findings below.
- Base-chain consensus (Ethereum PoS, the chain's validator set, the canonical Deposit Contract at 0x00000000219ab540356cBB839Cbe05303d7705Fa) is the SUBSTRATE, not a dependency, for any protocol deployed on that chain. Do not list "depends on Ethereum" as a finding.
- Oracles or other integrations used by DOWNSTREAM protocols that happen to read this protocol's token (e.g. Chainlink stETH/USD consumed by Aave) are NOT this protocol's dependencies. Count only what THIS protocol's contracts call or trust on-chain. If a feed or contract appears in the protocol's docs only as reference material for third-party integrators, EXCLUDE IT ENTIRELY — do not log it as a finding even with a "peripheral" or "referenced only" caveat.
- "Upgradeable admin can change things" belongs to the CONTROL slice; only count it here when the upgrade surface lets governance silently swap an external dependency (see A9).

MANDATORY INSPECTION CHECKLIST (every item below must appear in evidence[] OR unknowns[]):
- A1. External contract calls. Enumerate every external contract the core contracts call or read from (oracles, price feeds, AMM pools, lending pools, staking/deposit contracts, yield wrappers). For each, identify the address, the provider, and what user-facing function of this protocol would break or mis-price if that external contract paused, mis-reported, or behaved adversarially. Grep for "oracle", "aggregator", "getPrice", "latestAnswer", "chainlink", "pyth", "redstone" as a starting point.
- A2. Off-chain actor committees reporting INTO the protocol. Oracle committees, guardian multisigs, DAO-selected validator sets acting as protocol reporters, exit-bus signers, fraud-proof challengers. For each, record committee size, quorum, who picks the members, and what mis-reporting could do (mint, burn, finalize withdrawal, freeze). Distinguish this from governance admins (control slice). NOTE ON STAKING PROTOCOLS: validator slashing and node-operator misbehavior are properties of the base-chain substrate, NOT external dependencies, when the operator set is diversified enough that a coordinated failure caps at <5% principal loss. Count validator/operator risk under A2 ONLY if the operator set is small, non-diversified, or lacks bonding / slashing-insurance / diversification mitigations. A curated set of 30+ independent operators with documented diversification falls under the mitigated path; a 3-operator LST does not. Do not cite the protocol's own risk disclosure as evidence that operator failure = principal loss unless you also check the diversification and bond mitigations.
- A3. Bridge / cross-chain messaging dependencies. Only count bridges that carry material TVL or are required for a core user flow. For each, name the bridge operator (canonical L1↔L2, LayerZero, Wormhole, Axelar, custom multisig), the trust model (canonical, optimistic, light-client, guardian set), and what fraction of TVL or users ride on it. "wstETH exists on 15 chains" is not a finding unless material TVL sits there. Before listing any non-primary chain deployment as a dependency, verify it is still operational as of analysis_date — retired or sunset deployments (e.g., Lido-on-Terra, Lido-on-Solana) belong in unknowns[] or should be omitted, never cited as a current dependency.
- A4. Nested collateral / restaking chains. For restaking / LRT / receipt-of-receipt designs: record the depth of the collateral chain, every actor with slashing or freezing power at each level, and whether a failure N levels deep propagates to user principal here.
- A5. Fork lineage (silent check). If DeFiLlama's forkedFrom is non-empty, record it as one finding and move on. If empty, do NOT add a placeholder finding; it adds noise.
- A6. Fallback mechanisms and circuit breakers. What catches an external failure? Sanity-check contracts on oracle reports, rebase bounds, pause paths triggered by bad prices, second-opinion oracles, max-per-block throughput caps, withdrawal queues that absorb bad reports. Record which A1–A4 risks are mitigated by which fallback, and which are unmitigated. For EACH fallback you cite, state its activation status explicitly: (i) LIVE and enforcing on-chain today, (ii) DEPLOYED but not yet wired / activated (e.g., interface exists but the address is zero or the role is unassigned), or (iii) DOCUMENTED / PROPOSED only (forum post, LIP draft, audit pending). Only (i) counts as mitigation for the grade. A fallback in state (ii) or (iii) should be noted but must not reduce the risk in your steel-man or verdict. If you cannot determine activation status, add an unknowns[] entry rather than assume it is live.
- A7. Sequencer / L1-liveness dependency beyond the base-chain substrate. For L2-deployed protocols: a centralized sequencer or DA committee can freeze the protocol even if its own contracts are fine. Record the sequencer/DA trust model. "It's on Ethereum L1" counts as no additional liveness dependency beyond substrate.
- A8. Keeper / relayer / off-chain bot liveness. Protocols that need permissionless-but-necessary off-chain actors (liquidation bots, auto-compounders, deposit relayers, intent solvers). Record whether the role is permissionless, what degrades if nobody runs it (yield paused, bad debt accumulates, positions go stale), and whether the failure mode is graceful or catastrophic.
- A9. Governance-mutable dependency surface. Can an admin or DAO action silently INTRODUCE a new dependency — swap the oracle address, register a new staking module that calls an untrusted contract, add a new bridge — without an exit window for users? Check the upgrade / router / module-registry contracts. Answer: which dependencies are governance-mutable, who holds that power, and whether there is a timelock or exit window.

STEEL-MAN (per Hard Rule 13): write one-sentence strongest arguments for red, orange, and green using the A1–A9 findings.

IMPACTED TVS ESTIMATE: the headline MUST include a rough impacted-TVS figure — the fraction of protocol TVS that could be lost or frozen if the worst-unmitigated dependency you identified failed. Use "~X%" if exact numbers are unavailable, "<1%" for de minimis, "unclear" only if A1–A9 left the question genuinely open (in which case grade=unknown is usually correct). Do NOT substitute qualitative phrases like "significant" — give a number or bracket.

GRADE ANCHORS (mapped to DefiScan v1 stages):
- green = Stage 2 equivalent. Failure of any external dependency cannot cause loss of user principal or unclaimed yield. Either there are no material external dependencies, or every critical one has a documented fallback (A6) that keeps users whole. Governance cannot silently introduce new dependencies without an exit window (A9). Impacted TVS under any single-dependency failure: effectively 0.
- orange = Stage 1 equivalent. Failure of some external dependency can cause loss of unclaimed yield, or can materially change expected performance (pause withdrawals, freeze positions, degrade price quality), but cannot cause loss of principal. Committee-based oracles with sanity checks, canonical-only bridges, fallback paths that exist but are incomplete, or governance-mutable dependencies protected by a ≥7-day timelock. Impacted TVS is bounded and recoverable.
- red = Stage 0 equivalent. Failure of an external dependency CAN cause theft or loss of principal. Examples: single-provider oracle with no sanity check or fallback, material TVL on a non-canonical bridge with a guardian multisig, governance can hot-swap oracles or add staking modules with no timelock or exit window, unmitigated keeper-liveness dependency where positions become insolvent if bots stop. Impacted TVS is material.
- unknown = checklist incomplete after inspecting source + verified contracts. Prefer unknown over guessing when A1/A6 could not be reconstructed.

PROMPT-META CHECK (per Hard Rule 17): before finalizing, verify the verdict cites concrete contract addresses, docs, or code — not the rubric itself. If your verdict says "the protocol belongs to a category the rubric marks red", rewrite it with the A1–A9 finding that actually justifies the grade, or drop to grade=unknown.`;
