export const controlBody = `### Slice: CONTROL

Evaluate who can change the protocol's rules, how fast, and how broadly.

MANDATORY INSPECTION CHECKLIST (every item below must appear in evidence[] OR unknowns[]):
- C1. For each address you assess: who is the contract owner / admin / pendingAdmin / governor (read these on the block explorer's "Read Contract" tab). When a protocol has multiple major versions deployed (v2/v3/v4, or v1/v2), perform C1 reads on the NEWEST deployment's admin/owner separately — newer deployments often have different (and sometimes weaker) control surfaces than the legacy core. If you did not read a newer-version owner on-chain, list it in unknowns[] with the checklist code.
- C2. Upgrade mechanism: transparent proxy / UUPS / Beacon / Diamond / immutable. Identify the proxy admin address. Check upgradeability of the GOVERNANCE contracts too, not just the core protocol — a GovernorBravoDelegator / Aragon Voting / OZ Governor is often itself a proxy whose admin is the Timelock, which means governance can rewrite its own voting rules through the same path it uses for protocol changes. Record this explicitly. Important asymmetry: when the fund-holding core contracts (AMM pools, lending markets, vaults) are immutable AND governance has no admin path that reaches them, an upgradable Governor/Timelock is a T3-only power (it can rewrite voting rules but cannot touch user funds) and must NOT drag the verdict below green on that basis alone — see grade rules. Upgradable periphery (routers, quoters, frontends) that users can route around is similarly not a T1 path. Only call the protocol "mixed" upgradability in a way that affects the grade if you can name a concrete function on the upgradable surface that reaches a T1 or T2 power on user funds.
- C3. EXECUTION PATH (enumerate every stage, in order, with its delay in seconds).
  Modern protocols rarely have a single timelock — the operative path is usually a chain of contracts (e.g. voting contract → scheduler → timelock → executor, or governor → queue → execute, or Aragon Voting → DualGovernance → EmergencyProtectedTimelock → AdminExecutor). Walk the full call chain from "vote passes" to "implementation slot written." For each stage, record:
    a) the contract address,
    b) the delay constant (name + value in seconds),
    c) the Read Contract function / storage slot you read it from.
  Do NOT stop at the first timelock-shaped contract you find — if the admin of the core proxy is itself called by a further contract, keep walking.
  The timelock that matters for grading is the SUM OF DELAYS ON THE UNCONTESTED FAST PATH — the shortest time a proposal with no opposition can go from submission to executable state. Dynamic / contested extensions (veto signaling, rage quit, escrow-based delay) are modifiers, not the basis — note them separately.
- C4. Enumerate EVERY multisig with reachable control over the protocol — main proxy admin, emergency activation, emergency execution, reseal / pause, gate-seal committees, tiebreaker, per-module admins. Do not stop at the "main" multisig. Enumerate multisigs even when their scope is "only" operational (incentives, grants, parameter tuning, council-style committees) — record their power scope explicitly so a reader can see they are NOT on the upgrade path. A C4 that lists only the timelock/governor on a protocol with a known council or ops multisig is incomplete. For each, record: (a) address, (b) threshold / total signers, (c) signer identities and their affiliations classified as insider (team, paid auditors under ongoing engagement, mandated service providers) vs non-insider (independent community members, unaffiliated security researchers), (d) the specific power it holds (upgrade, pause, parameter, etc.). Missing emergency or module-level multisigs is an incomplete C4.
- C5. On-chain governance: is there a Governor / GovernorBravo / OZ Governor / Aragon Voting with token-weighted voting? Record proposal threshold, voting period, quorum, and the timelock delay between queue and execute. Every numeric constant you cite here must either come from a Read Contract call you can link to, or be listed in unknowns[] prefixed with its checklist code. If votingDelay / votingPeriod are denominated in BLOCKS, convert to seconds using the chain's CURRENT block time (Ethereum mainnet ≈ 12s post-Merge, not the 15s assumed in older Compound/Bravo deployments). Cite both the block count and the converted seconds — a "7-day" period in legacy comments is often ~5.6 days at current block times.
- C6. EMERGENCY POWERS: is there a separate emergency-pause / guardian role with a different (often shorter) time cap or different actor than the main upgrade authority? Record it explicitly — many protocols separate "fast emergency multisig" from "slow governance upgrade."
- C7. POWER TIER (blast radius). For each privileged path you identified in C3–C6, classify the WORST thing that path can do, choosing the highest applicable tier. Cite the specific function name and any on-chain bound (capped value, range, percentage limit) — tier claims without a named function are unsupported.
    T1 — FUND-CRITICAL: replace implementation of contracts holding user funds; change AMM math / accounting / collateral logic; mint unbacked debt or unbacked shares; pause withdrawals; drain protocol treasury that includes user funds; change oracle to an attacker-controlled source; replace the upgrade admin with an EOA.
    T2 — ECONOMICALLY MATERIAL: change fee parameters within bounded ranges; redirect protocol fees to a new recipient; add or remove markets / collateral types; bounded inflation or token mint within a hard-capped schedule; spend protocol-owned (non-user) treasury.
    T3 — GOVERNANCE-INTERNAL: change voting rules, quorum, voting period, or proposal threshold; upgrade the Governor itself; rotate the Timelock admin; mint governance tokens within a capped annual schedule.
    T4 — OPERATIONAL: incentives distribution, grants, ENS/frontend canonicalization, deployment coordination, periphery router deprecation that does not affect existing positions.
  The grade is set by the HIGHEST tier reachable on the uncontested fast path, not the median. If the fast path can reach T1, you are grading T1 — even if 90% of historical proposals were T4. State the tier and the binding function in the verdict.

### Read Contract discipline (applies to C3, C4, C5)

Every numeric constant you cite — timelock delays, voting periods, multisig thresholds, quorum percentages, proposal thresholds — must come from ONE of:
  (a) a block-explorer Read Contract view function call, cited with a URL and fetched_at; or
  (b) an entry in unknowns[] prefixed with the checklist code.

Citing a docs page or blog post as the sole source for a value that is also readable on-chain is not enough — docs and blog posts drift, on-chain constants do not. Docs are fine as CORROBORATION but cannot be the only citation. Empty unknowns[] on a protocol with more than ~3 admin-class contracts will be flagged by the quorum bot as suspiciously thorough-looking; if you did not actually read a given constant on-chain during this run, say so in unknowns[]. If unknowns[] is empty, you are asserting that every numeric constant in C3/C5 came from a Read Contract URL listed in evidence[] — reviewers will sample-check. Fabricated thoroughness (citing docs as if they were on-chain reads, or restating constructor args from a deployment tx as if they were live storage reads) is worse than an honest unknowns[] entry.

Then write the steel-man section per Hard Rule 11.

Security Council standard (used in the grade rules below): a multisig qualifies as a "Security Council" only if ALL of the following hold — ≥7 signers, ≥51% threshold, ≥50% non-insider signers, and every signer publicly announced by name or pseudonym. Insider means anyone in the protocol's inner circle: team members, paid auditors under ongoing engagement, and mandated service providers. A multisig failing ANY of these four criteria is NOT a Security Council, regardless of how reputable the signers are individually.

Grade rules (apply the timelock bar conditional on the highest C7 tier reachable on the fast path):
- green   = highest reachable tier is T3 or T4 regardless of timelock (governance rewriting itself or doing operational work cannot directly endanger user funds), OR T2 reachable with uncontested-fast-path delay ≥7 days, OR T1 reachable only via immutable contracts (i.e. T1 is unreachable), OR T1 reachable with uncontested-fast-path delay ≥7 days combined with a Security Council multisig (as defined above), OR T1 reachable with uncontested-fast-path delay ≥7 days through active on-chain governance with broad token distribution.
- orange  = T2 reachable with uncontested-fast-path delay >0 but <7 days, OR T1 reachable with uncontested-fast-path delay >0 but <7 days, OR a multisig that fails one or more Security Council criteria (too few signers, threshold <51%, majority-insider, or anonymous signers) sits on a T1 or T2 path, OR unclear upgrade authority on a T1/T2 path, OR governance exists with very short timelock or low quorum on a T1/T2 path.
- red     = T1 reachable with no timelock by a single EOA or 2-of-3 multisig, OR a T1 upgrade admin that is not a smart contract you can audit.
- unknown = you completed the checklist but still cannot determine the upgrade authority OR cannot classify the highest tier reachable on the main contracts.

Power-tier weighting rationale: the rubric grades on blast radius, not just speed. A 2-day timelock on a T1 power (rewrite swap math) is materially worse than a 2-day timelock on a T2 power (toggle a bounded fee switch within an enforced range), which is in turn materially worse than a 2-day timelock on a T3 power (change quorum). The 7-day exit-window bar applies to T1 and T2 because those powers can move user funds or extract value; T3 powers cannot directly endanger funds — captured governance rewriting itself still has to clear the T1/T2 timelocks to touch anything users hold, so the T3 timelock value matters far less. T4 powers do not require any timelock for grading.

Caveats on tiering:
  - "Bounded" must be enforced ON-CHAIN to count as T2. A function that says it sets fees but has no upper bound check is T1, not T2 — cite the bound check.
  - Recurring T2 economic extraction (e.g. fee redirect to attacker-controlled address with no rate limit) approaches T1 over time. If a single proposal can permanently redirect all future protocol revenue, treat it as T1.
  - T3 assumes the governance contract cannot itself authorize a T1/T2 action without going through the same timelock. If governance can self-upgrade to a version that bypasses the timelock, T3 collapses into T1.
  - Do not downgrade tier by hand-waving ("realistically governance would never…"). Tier on what the contract permits, not what feels likely.

Note on dynamic / dual-governance timelocks (Lido-style, Compound-style escrow veto, etc.): the rubric grades on the uncontested path deliberately, because that is the path most upgrades actually take. A dynamic extension that only fires under stake-weighted opposition is a real user protection and should be named in the green steel-man, but it does not lift an orange fast path into green — state this tension in the verdict rather than collapsing it.

Note on immutable cores with upgradable governance (Uniswap-style): if the contracts that hold user funds are immutable and have no admin-reachable function that can move, freeze, or re-route those funds, then the highest tier reachable on the upgrade path is T3 — governance can rewrite itself but cannot follow that path back to user funds. Per the grade rules, "highest reachable tier is T3 or T4" is green regardless of timelock. Do NOT grade this as orange / "mixed" merely because the Governor is a proxy; that observation belongs in C2 as factual record, not as a downgrade. The downgrade only applies if you can cite a concrete function on the upgradable surface that reaches T1 or T2 (e.g. a privileged hook, an upgradable factory that controls fund-routing, a fee-switch that can redirect protocol revenue without bound).

Note on the 7-day bar: this threshold reflects the exit-window standard — users need enough notice after a queued upgrade to withdraw if they disagree. The ability-to-exit slice grades the exit side; this slice grades the delay side; both must hold for users to actually benefit from the delay.`;
