export const controlBody = `### Slice: CONTROL

Evaluate who can change the protocol's rules, how fast, and how broadly.

MANDATORY INSPECTION CHECKLIST (every item below must appear in evidence[] OR unknowns[]):
- C1. For each address you assess: who is the contract owner / admin / pendingAdmin / governor (read these on the block explorer's "Read Contract" tab). When a protocol has multiple major versions deployed (v2/v3/v4, or v1/v2), perform C1 reads on the NEWEST deployment's admin/owner separately — newer deployments often have different (and sometimes weaker) control surfaces than the legacy core. If you did not read a newer-version owner on-chain, list it in unknowns[] with the checklist code.
- C2. Upgrade mechanism: transparent proxy / UUPS / Beacon / Diamond / immutable. Identify the proxy admin address. Check upgradeability of the GOVERNANCE contracts too, not just the core protocol — a GovernorBravoDelegator / Aragon Voting / OZ Governor is often itself a proxy whose admin is the Timelock, which means governance can rewrite its own voting rules through the same path it uses for protocol changes. Record this explicitly.
- C3. EXECUTION PATH (enumerate every stage, in order, with its delay in seconds).
  Modern protocols rarely have a single timelock — the operative path is usually a chain of contracts (e.g. voting contract → scheduler → timelock → executor, or governor → queue → execute, or Aragon Voting → DualGovernance → EmergencyProtectedTimelock → AdminExecutor). Walk the full call chain from "vote passes" to "implementation slot written." For each stage, record:
    a) the contract address,
    b) the delay constant (name + value in seconds),
    c) the Read Contract function / storage slot you read it from.
  Do NOT stop at the first timelock-shaped contract you find — if the admin of the core proxy is itself called by a further contract, keep walking.
  The timelock that matters for grading is the SUM OF DELAYS ON THE UNCONTESTED FAST PATH — the shortest time a proposal with no opposition can go from submission to executable state. Dynamic / contested extensions (veto signaling, rage quit, escrow-based delay) are modifiers, not the basis — note them separately.
- C4. Enumerate EVERY multisig with reachable control over the protocol — main proxy admin, emergency activation, emergency execution, reseal / pause, gate-seal committees, tiebreaker, per-module admins. Do not stop at the "main" multisig. Enumerate multisigs even when their scope is "only" operational (incentives, grants, parameter tuning, council-style committees) — record their power scope explicitly so a reader can see they are NOT on the upgrade path. A C4 that lists only the timelock/governor on a protocol with a known council or ops multisig is incomplete. For each, record: (a) address, (b) threshold / total signers, (c) signer identities and their affiliations classified as insider (team, paid auditors under ongoing engagement, mandated service providers) vs non-insider (independent community members, unaffiliated security researchers), (d) the specific power it holds (upgrade, pause, parameter, etc.). Missing emergency or module-level multisigs is an incomplete C4.
- C5. On-chain governance: is there a Governor / GovernorBravo / OZ Governor / Aragon Voting with token-weighted voting? Record proposal threshold, voting period, quorum, and the timelock delay between queue and execute. Every numeric constant you cite here must either come from a Read Contract call you can link to, or be listed in unknowns[] prefixed with its checklist code. If votingDelay / votingPeriod are denominated in BLOCKS, convert to seconds using the chain's CURRENT block time (Ethereum mainnet ≈ 12s post-Merge, not the 15s assumed in older Compound/Bravo deployments). Cite both the block count and the converted seconds — a "7-day" period in legacy comments is often ~5.6 days at current block times.
- C6. EMERGENCY POWERS: is there a separate emergency-pause / guardian role with a different (often shorter) time cap or different actor than the main upgrade authority? Record it explicitly — many protocols separate "fast emergency multisig" from "slow governance upgrade."

### Read Contract discipline (applies to C3, C4, C5)

Every numeric constant you cite — timelock delays, voting periods, multisig thresholds, quorum percentages, proposal thresholds — must come from ONE of:
  (a) a block-explorer Read Contract view function call, cited with a URL and fetched_at; or
  (b) an entry in unknowns[] prefixed with the checklist code.

Citing a docs page or blog post as the sole source for a value that is also readable on-chain is not enough — docs and blog posts drift, on-chain constants do not. Docs are fine as CORROBORATION but cannot be the only citation. Empty unknowns[] on a protocol with more than ~3 admin-class contracts will be flagged by the quorum bot as suspiciously thorough-looking; if you did not actually read a given constant on-chain during this run, say so in unknowns[]. If unknowns[] is empty, you are asserting that every numeric constant in C3/C5 came from a Read Contract URL listed in evidence[] — reviewers will sample-check. Fabricated thoroughness (citing docs as if they were on-chain reads, or restating constructor args from a deployment tx as if they were live storage reads) is worse than an honest unknowns[] entry.

Then write the steel-man section per Hard Rule 11.

Security Council standard (used in the grade rules below): a multisig qualifies as a "Security Council" only if ALL of the following hold — ≥7 signers, ≥51% threshold, ≥50% non-insider signers, and every signer publicly announced by name or pseudonym. Insider means anyone in the protocol's inner circle: team members, paid auditors under ongoing engagement, and mandated service providers. A multisig failing ANY of these four criteria is NOT a Security Council, regardless of how reputable the signers are individually.

Grade rules:
- green   = immutable contracts, OR uncontested-fast-path delay ≥7 days combined with a Security Council multisig (as defined above), OR active on-chain governance with uncontested-fast-path delay ≥7 days and broad token distribution.
- orange  = uncontested-fast-path delay >0 but <7 days (even if a dynamic / contested timelock can extend above 7 days — note the extension as a steel-man for green, but grade on the fast path), OR a multisig that fails one or more Security Council criteria (too few signers, threshold <51%, majority-insider, or anonymous signers), OR unclear upgrade authority, OR governance exists but with very short timelock or low quorum.
- red     = a single EOA or 2-of-3 multisig can upgrade with no timelock, OR the upgrade admin is not a smart contract you can audit.
- unknown = you completed the checklist but still cannot determine the upgrade authority for the main contracts.

Note on rule changes vs parameter changes: distinguish RULE changes (math, swap logic, accounting, who can hold/move funds) from PARAMETER changes (fee tier enable, treasury spend, fee recipient, bounded fee switch). If the core swap/accounting contracts are immutable and governance can only toggle bounded parameters that cannot directly seize or freeze user funds, grade on the immutable core (green if the governance path also meets the ≥7-day bar). Reserve orange for cases where governance can change rules that materially affect fund safety on a <7-day path. State this distinction in the verdict when it is the load-bearing reason for the grade.

Note on dynamic / dual-governance timelocks (Lido-style, Compound-style escrow veto, etc.): the rubric grades on the uncontested path deliberately, because that is the path most upgrades actually take. A dynamic extension that only fires under stake-weighted opposition is a real user protection and should be named in the green steel-man, but it does not lift an orange fast path into green — state this tension in the verdict rather than collapsing it.

Note on the 7-day bar: this threshold reflects the exit-window standard — users need enough notice after a queued upgrade to withdraw if they disagree. The ability-to-exit slice grades the exit side; this slice grades the delay side; both must hold for users to actually benefit from the delay.`;
