export const controlBody = `### Slice: CONTROL

Evaluate who can change the protocol's rules, how fast, and how broadly.

### Step 0 — Capability probe & Data Gathering Mode (do this before anything else)

Before producing JSON, you MUST attempt at least two direct fetches in this run and observe the result of each:
  (a) the protocol's website / docs page (use the \`protocol.website\` pinned input above), AND
  (b) one of the pre-built surfacer URLs in the "Pre-built read-API surfacer URLs" block at the top of the preamble (or the protocol's primary block-explorer page if no surfacer URL is pinned).

For each attempted fetch, record what you observed: tool used (any fetch / search / browse / url-context / url-loading tool exposed in your environment counts — not just "web_fetch"), the URL, and the result (response body summary if it succeeded; HTTP status, allowlist rejection text, or "tool not present in this environment: <name you tried>" if it failed).

**Search-only fast path:** if your environment exposes a search-grounding tool but no raw HTTP client (no \`web_fetch\`, no \`browser\`, no \`url_context\` — only \`google_search\` / \`google:search\` / Bing grounding / Perplexity tools / similar), you may skip the direct URL fetches in (a) and (b) and go straight to Data Gathering Mode below. Direct URL fetches against unindexed JSON endpoints will always fail under search-only tools — that is a known environment shape, not a tool error worth probing for. To claim this fast path you MUST name the search tool you have (e.g. "available tools: google_search; no raw fetch tool exposed") in your first \`unknowns[]\` entry; "I'm search-only" without naming the actual tool is treated as the laziness path and zero-weighted.

If EITHER direct probe succeeded, you have working fetch capability — proceed with the assessment.

**If both direct probes failed, DO NOT STOP. You must enter Data Gathering Mode before claiming blocked.** Tool errors on a direct fetch ("allowlist rejection", "404", "no tool named X") tell you nothing about whether SEARCH is available. Hitting one error and short-circuiting to \`grade="unknown"\` is a failure mode — the prompt explicitly grants you permission to keep trying with different tools.

Data Gathering Mode (mandatory when direct fetches fail):
  1. Issue at least TWO broad search queries via any search-grounding tool exposed in your environment (e.g. \`google_search\`, Bing grounding, Perplexity tools). Suggested queries: the protocol name + "Etherscan", protocol name + "official docs", protocol name + "GitHub", protocol name + "audit report".
  2. Use \`site:\` operators as a proxy when direct URL fetching is blocked: \`site:etherscan.io "0x<address>"\`, \`site:github.com <protocol> contract\`, \`site:<docs-domain> admin OR multisig OR governance\`. If the search-grounding tool returns the underlying page body for a site:-narrowed query, that page URL is fetched evidence and goes in \`evidence[]\` with a fetched_at timestamp (see preamble's snippet-vs-grounded-body distinction).
  3. If the search returns the page body, set \`grading_basis: "off-chain-only"\` and CONTINUE the assessment with whatever you can extract.

You may ONLY return \`grade="unknown"\` with empty \`evidence[]\` if BOTH direct fetches AND at least two broad search queries returned absolutely nothing useful. In that case, log the attempted query strings and the observed-zero-results outcome in \`unknowns[]\` (e.g. \`"C1-offchain: searched 'Tether USDT contract owner' and 'site:etherscan.io 0xdAC17...' via google_search; both returned zero indexed results / no grounded body"\`). Claiming "tools disabled" without logging attempted search queries is a zero-weight non-submission.

This step is non-negotiable. Describing a hypothetical attempt ("I would have tried X but no tool was available") does not satisfy it — actually invoke whatever tool you have and report what came back.

### Partial discovery is a successful run (the ratchet)

If you can find a contract's ABI, audit report, or docs page but cannot read live state (\`owner()\`, \`getOwners()\`, \`MIN_DELAY\`) because RPC reads or block-explorer Read Contract panels failed, you MUST still record the partial discovery rather than emitting an empty submission:

  - Extract privileged functions from the ABI you found and log them in \`rationale.findings\` with their checklist code (e.g. \`"C7: Controller exposes mint() and pause(); ABI surfaces a T1-tier mint power on the upgradable surface"\`). Cite the ABI URL in \`evidence[]\`.
  - Populate \`protocol_metadata\` with every github / docs_url / audits / admin_addresses entry you can scrape from the off-chain corpus. Each becomes a seed for the next run's \`address_book\`.
  - Set \`grade="unknown"\` and state in the verdict what specifically remained unverified — e.g. "ABI surfaces T1 mint/burn powers on the Controller, but the live owner identity and timelock delays were unverified in this run."
  - Do NOT invent a grade based on the ABI alone; ABI shape tells you what the contract CAN do, not who currently holds the powers or whether a timelock fronts them. The grade is for the live control surface, which requires on-chain reads.

The ratchet is the design: this run produces seeds (addresses, audit URLs, ABI evidence), the next run reads them on-chain. A submission that documents partial discovery + unverified gaps is a real contribution; a submission with empty \`evidence[]\` because the model gave up after the first tool error is not.

MANDATORY INSPECTION CHECKLIST (every item below must appear in evidence[] OR unknowns[]):
- C1. For each address you assess: who is the contract owner / admin / pendingAdmin / governor — read these via the block explorer's "Read Contract" tab OR https://defipunkd.com/api/contract/read?chainId=<id>&address=0x...&method=owner (use the BARE method name without parens; similarly &method=admin, &method=pendingOwner, &method=governor). For Safes use the shortcut https://defipunkd.com/api/safe/owners?chainId=<id>&address=0x.... When a protocol has multiple major versions deployed (v2/v3/v4, or v1/v2), perform C1 reads on the NEWEST deployment's admin/owner separately — newer deployments often have different (and sometimes weaker) control surfaces than the legacy core. If you did not read a newer-version owner on-chain, list it in unknowns[] with the checklist code.
- C2. Upgrade mechanism: transparent proxy / UUPS / Beacon / Diamond / immutable. Identify the proxy admin address. Check upgradeability of the GOVERNANCE contracts too, not just the core protocol — a GovernorBravoDelegator / Aragon Voting / OZ Governor is often itself a proxy whose admin is the Timelock, which means governance can rewrite its own voting rules through the same path it uses for protocol changes. Record this explicitly. Important asymmetry: when the fund-holding core contracts (AMM pools, lending markets, vaults) are immutable AND governance has no admin path that reaches them, an upgradable Governor/Timelock is a T3-only power (it can rewrite voting rules but cannot touch user funds) and must NOT drag the verdict below green on that basis alone — see grade rules. Upgradable periphery (routers, quoters, frontends) that users can route around is similarly not a T1 path. Only call the protocol "mixed" upgradability in a way that affects the grade if you can name a concrete function on the upgradable surface that reaches a T1 or T2 power on user funds.
- C3. EXECUTION PATH (enumerate every stage, in order, with its delay in seconds).
  Modern protocols rarely have a single timelock — the operative path is usually a chain of contracts (e.g. voting contract → scheduler → timelock → executor, or governor → queue → execute, or Aragon Voting → DualGovernance → EmergencyProtectedTimelock → AdminExecutor). Walk the full call chain from "vote passes" to "implementation slot written." For each stage, record:
    a) the contract address,
    b) the delay constant (name + value in seconds),
    c) the Read Contract function / storage slot you read it from — cite the block-explorer URL or the DeFiPunkd API URL (e.g. /api/contract/read?...&method=MIN_DELAY&block=<n>; pinning &block=<n> makes the citation content-addressed).
  Do NOT stop at the first timelock-shaped contract you find — if the admin of the core proxy is itself called by a further contract, keep walking.
  The timelock that matters for grading is the SUM OF DELAYS ON THE UNCONTESTED FAST PATH — the shortest time a proposal with no opposition can go from submission to executable state. Dynamic / contested extensions (veto signaling, rage quit, escrow-based delay) are modifiers, not the basis — note them separately.
- C4. Enumerate EVERY multisig with reachable control over the protocol — main proxy admin, emergency activation, emergency execution, reseal / pause, gate-seal committees, tiebreaker, per-module admins. For each Safe address you find, fetch threshold + owners + version in one call via https://defipunkd.com/api/safe/owners?chainId=<id>&address=0x... (the response includes the raw eth_call data, so the URL itself is citable evidence). Do not stop at the "main" multisig. Enumerate multisigs even when their scope is "only" operational (incentives, grants, parameter tuning, council-style committees) — record their power scope explicitly so a reader can see they are NOT on the upgrade path. A C4 that lists only the timelock/governor on a protocol with a known council or ops multisig is incomplete. For each, record: (a) address, (b) threshold / total signers, (c) signer identities and their affiliations classified as insider (team, paid auditors under ongoing engagement, mandated service providers) vs non-insider (independent community members, unaffiliated security researchers), (d) the specific power it holds (upgrade, pause, parameter, etc.). Missing emergency or module-level multisigs is an incomplete C4.
- C5. On-chain governance: is there a Governor / GovernorBravo / OZ Governor / Aragon Voting with token-weighted voting? Record proposal threshold, voting period, quorum, and the timelock delay between queue and execute. Every numeric constant you cite here must either come from a Read Contract call you can link to, or be listed in unknowns[] prefixed with its checklist code. If votingDelay / votingPeriod are denominated in BLOCKS, convert to seconds using the chain's CURRENT block time (Ethereum mainnet ≈ 12s post-Merge, not the 15s assumed in older Compound/Bravo deployments). Cite both the block count and the converted seconds — a "7-day" period in legacy comments is often ~5.6 days at current block times.
- C6. EMERGENCY POWERS: is there a separate emergency-pause / guardian role with a different (often shorter) time cap or different actor than the main upgrade authority? Record it explicitly — many protocols separate "fast emergency multisig" from "slow governance upgrade."
- C7. POWER TIER (blast radius). For each privileged path you identified in C3–C6, classify the WORST thing that path can do, choosing the highest applicable tier. Cite the specific function name and any on-chain bound (capped value, range, percentage limit) — tier claims without a named function are unsupported.
    T1 — FUND-CRITICAL: replace implementation of contracts holding user funds; change AMM math / accounting / collateral logic; mint unbacked debt or unbacked shares; pause withdrawals; drain protocol treasury that includes user funds; change oracle to an attacker-controlled source; replace the upgrade admin with an EOA.
    T2 — ECONOMICALLY MATERIAL: change fee parameters within bounded ranges; redirect protocol fees to a new recipient; add or remove markets / collateral types; bounded inflation or token mint within a hard-capped schedule; spend protocol-owned (non-user) treasury.
    T3 — GOVERNANCE-INTERNAL: change voting rules, quorum, voting period, or proposal threshold; upgrade the Governor itself; rotate the Timelock admin; mint governance tokens within a capped annual schedule.
    T4 — OPERATIONAL: incentives distribution, grants, ENS/frontend canonicalization, deployment coordination, periphery router deprecation that does not affect existing positions.
  The grade is set by the HIGHEST tier reachable on the uncontested fast path, not the median. If the fast path can reach T1, you are grading T1 — even if 90% of historical proposals were T4. State the tier and the binding function in the verdict.

### Read Contract discipline (applies to C3, C4, C5)

Every numeric constant you cite — timelock delays, voting periods, multisig thresholds, quorum percentages, proposal thresholds — must come from ONE of:
  (a) a block-explorer Read Contract view function call, cited with a URL and fetched_at; or
  (a-bis) a DeFiPunkd /api/contract/read or /api/safe/owners URL — preferred when you can pin &block=<n>, since the response is content-addressed (anyone re-running the URL gets a byte-identical answer with the raw return data inline); or
  (b) an entry in unknowns[] prefixed with the checklist code.

Citing a docs page or blog post as the sole source for a value that is also readable on-chain is not enough — docs and blog posts drift, on-chain constants do not. Docs are fine as CORROBORATION but cannot be the only citation. Empty unknowns[] on a protocol with more than ~3 admin-class contracts will be flagged by the quorum bot as suspiciously thorough-looking; if you did not actually read a given constant on-chain during this run, say so in unknowns[]. If unknowns[] is empty, you are asserting that every numeric constant in C3/C5 came from a Read Contract URL listed in evidence[] — reviewers will sample-check. Fabricated thoroughness (citing docs as if they were on-chain reads, or restating constructor args from a deployment tx as if they were live storage reads) is worse than an honest unknowns[] entry.

### Off-chain-only fallback (when on-chain reads are genuinely unavailable in this run)

This is a TRIGGER-GATED fallback for environments where the model has working web fetch but cannot reach on-chain reads (defipunkd /api/contract/read and /api/safe/owners are blocked, AND block-explorer Read Contract panels did not render). It is NOT a shortcut to skip on-chain work. If you can fetch on-chain reads, you must — this section does not apply.

To opt in, set the top-level output field \`grading_basis: "off-chain-only"\` and record at least one entry in unknowns[] documenting the failed on-chain fetch attempt, prefixed with the relevant checklist code and the \`-offchain\` suffix. Example: "C1-offchain: tried /api/contract/read for owner() at 0xABC and got allowlist rejection; tried etherscan.io/address/0xABC#readContract and the panel did not render in this environment".

When this fallback is active, the C1–C7 checklist remains binding, but the eligible substitute sources change. The substitute hierarchy, in priority order:

  1. Linked audit PDFs — these usually enumerate admin roles, multisig members, and timelock delays explicitly. Audits authored by the firms named in protocol_metadata.audits or in the pinned audit_links count; pirated copies on third-party blogs do not.
  2. Protocol governance forum posts (Discourse, Commonwealth, Aragon forum) that quote constants from a successful on-chain proposal — cite the post URL and the linked execution-tx URL even if you cannot follow the tx link.
  3. Official protocol docs pages with named addresses and roles. The page must be on a domain owned by the protocol (the docs_url metadata field anchors this).
  4. GitHub README / SECURITY.md / governance/*.md files at a pinned commit SHA in one of the linked repos.

FORBIDDEN substitutes (these are still fabrication, fallback or not): third-party blog posts, Twitter / X threads, search-result snippets, model memory, generic "well-known protocol" reasoning. The anti-fabrication gate from the preamble is unchanged — every cited URL must still have been fetched in this run.

REQUIRED DEGRADATION: any C-code that depends on a numeric constant (delay seconds, multisig threshold, quorum, voting period, proposal threshold, signer count) and is sourced ONLY from docs / forum / audit prose MUST also carry an unknowns[] entry with the \`-offchain\` suffix noting "value not re-read on-chain in this run; corroboration only — docs drift, on-chain constants do not". A C3/C5 numeric without that paired unknowns[] entry under off-chain-only basis is treated as fabricated thoroughness.

The grade you produce under off-chain-only basis is held to the same rubric below, but it will be downweighted by the quorum bot relative to on-chain submissions. That is the design — your run becomes a useful corroboration signal, not a substitute for contract state. If the off-chain corpus does not yield enough specifics to ground a grade, return grade="unknown" with the appropriate -offchain unknowns[] entries; do not stretch docs prose to cover gaps.

If SOME C-codes were readable on-chain in this run and others required the off-chain fallback, set \`grading_basis: "mixed"\`. The same -offchain suffix discipline applies to the codes that fell back. Pure on-chain runs use \`grading_basis: "on-chain"\` and need not include the \`grading_basis\` field at all (it defaults to "on-chain" when omitted).

Then write the steel-man section per Hard Rule 11.

Security Council standard (used in the grade rules below): a multisig qualifies as a "Security Council" only if ALL of the following hold — ≥7 signers, ≥51% threshold, ≥50% non-insider signers, and every signer publicly announced by name or pseudonym. Insider means anyone in the protocol's inner circle: team members, paid auditors under ongoing engagement, and mandated service providers. A multisig failing ANY of these four criteria is NOT a Security Council, regardless of how reputable the signers are individually.

Grade rules (apply the timelock bar conditional on the highest C7 tier reachable on the fast path):
- green   = highest reachable tier is T3 or T4 regardless of timelock (governance rewriting itself or doing operational work cannot directly endanger user funds), OR T2 reachable with uncontested-fast-path delay ≥7 days, OR T1 reachable only via immutable contracts (i.e. T1 is unreachable), OR T1 reachable with uncontested-fast-path delay ≥7 days combined with a Security Council multisig (as defined above), OR T1 reachable with uncontested-fast-path delay ≥7 days through active on-chain governance with broad token distribution.
- orange  = T2 reachable with uncontested-fast-path delay >0 but <7 days, OR T1 reachable with uncontested-fast-path delay >0 but <7 days, OR a multisig that fails one or more Security Council criteria (too few signers, threshold <51%, majority-insider, or anonymous signers) sits on a T1 or T2 path, OR unclear upgrade authority on a T1/T2 path, OR governance exists with very short timelock or low quorum on a T1/T2 path.
- red     = T1 reachable with no timelock by a single EOA or 2-of-3 multisig, OR a T1 upgrade admin that is not a smart contract you can audit.
- unknown = you completed the checklist but still cannot determine the upgrade authority OR cannot classify the highest tier reachable on the main contracts.

Power-tier weighting rationale: the rubric grades on blast radius, not just speed. A 2-day timelock on a T1 power (rewrite swap math) is materially worse than a 2-day timelock on a T2 power (toggle a bounded fee switch within an enforced range), which is in turn materially worse than a 2-day timelock on a T3 power (change quorum). The 7-day exit-window bar applies to T1 and T2 because those powers can move user funds or extract value; T3 powers cannot directly endanger funds — captured governance rewriting itself still has to clear the T1/T2 timelocks to touch anything users hold, so the T3 timelock value matters far less. T4 powers do not require any timelock for grading.

Caveats on tiering:
  - "Bounded" must be enforced ON-CHAIN to count as T2. A function that says it sets fees but has no upper bound check is T1, not T2 — cite the bound check.
  - Recurring T2 economic extraction (e.g. fee redirect to attacker-controlled address with no rate limit) approaches T1 over time. If a single proposal can permanently redirect all future protocol revenue, treat it as T1.
  - T3 assumes the governance contract cannot itself authorize a T1/T2 action without going through the same timelock. If governance can self-upgrade to a version that bypasses the timelock, T3 collapses into T1.
  - Do not downgrade tier by hand-waving ("realistically governance would never…"). Tier on what the contract permits, not what feels likely.

Note on dynamic / dual-governance timelocks (Lido-style, Compound-style escrow veto, etc.): the rubric grades on the uncontested path deliberately, because that is the path most upgrades actually take. A dynamic extension that only fires under stake-weighted opposition is a real user protection and should be named in the green steel-man, but it does not lift an orange fast path into green — state this tension in the verdict rather than collapsing it.

Note on immutable cores with upgradable governance (Uniswap-style): if the contracts that hold user funds are immutable and have no admin-reachable function that can move, freeze, or re-route those funds, then the highest tier reachable on the upgrade path is T3 — governance can rewrite itself but cannot follow that path back to user funds. Per the grade rules, "highest reachable tier is T3 or T4" is green regardless of timelock. Do NOT grade this as orange / "mixed" merely because the Governor is a proxy; that observation belongs in C2 as factual record, not as a downgrade. The downgrade only applies if you can cite a concrete function on the upgradable surface that reaches T1 or T2 (e.g. a privileged hook, an upgradable factory that controls fund-routing, a fee-switch that can redirect protocol revenue without bound).

Note on the 7-day bar: this threshold reflects the exit-window standard — users need enough notice after a queued upgrade to withdraw if they disagree. The ability-to-exit slice grades the exit side; this slice grades the delay side; both must hold for users to actually benefit from the delay.`;
